version: '3.8'  # Versão do Docker Compose

services:
  fastapi_app:  # Nome do serviço atualizado para refletir FastAPI
    build: .  # Indica que o Dockerfile está no diretório atual
    container_name: fastapi_container  # Nome do contêiner
    ports:
      - "8011:8011"
    environment:
      - UVICORN_CMD=uvicorn app:app --host 0.0.0.0 --port 8011 --reload  # Comando para rodar o servidor
    volumes:
      - .:/app  # Monta o diretório atual no contêiner para desenvolvimento
    restart: unless-stopped  # Reinicia o contêiner automaticamente, a menos que seja parado manualmente
